/*
 * DIO_confg.h
 *
 *  Created on: Jan 27, 2016
 *      Author: aya osama
 */

#ifndef _DIO_CONFG_H_
#define _DIO_CONFG_H_

/*Comment!: PIN_INITDIR Initial Direction */
/*Range!  : DIO_u8INPUT ~ّDIO_u8OUTPUT  	 */


#define DIO_u8PIN0_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN1_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN2_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN3_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN4_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN5_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN6_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN7_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN8_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN9_INITDIR 		DIO_u8INPUT
#define DIO_u8PIN10_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN11_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN12_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN13_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN14_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN15_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN16_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN17_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN18_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN19_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN20_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN21_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN22_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN23_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN24_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN25_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN26_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN27_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN28_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN29_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN30_INITDIR 	DIO_u8INPUT
#define DIO_u8PIN31_INITDIR 	DIO_u8INPUT



#endif /* DIO_CONFG_H_ */
